### ISSUE TITLE
vernemq on OSX 10.11 El Capitan does not compile

### ISSUE THREAD

**Issue by ckrey** [erlio/vernemq#68]
```
===> Compiling vmq_passwd
gcc vmq_passwd.c -lcrypto -o vmq_passwd
vmq_passwd.c:32:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
make[1]: *** [compile] Error 1
===> Hook for compile failed!

make: *** [rel] Error
```

El Capitan removed openssl from the include and library path.
When using cmake for other projects, it helps to override those.
```
cmake -DOPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2d_1/include -DOPENSSL_CRYPTO_LIBRARY=/usr/local/Cellar/openssl/1.0.2d_1/lib/libcrypto.dylib -DOPENSSL_SSL_LIBRARY=/usr/local/Cellar/openssl/1.0.2d_1/lib/libssl.dylib ..
```

Any hint where to check in `make rel`?

**Comment by ioolkos** [comment]
OK, thanks. My guess is adding -lcrypto and -lssl linking to your libcrypto.dylib and libssl.dylib to the [gcc command] (https://github.com/erlio/vmq_passwd/blob/master/c_src/Makefile) will help
I can only test later.

**Comment by ckrey** [comment]
To fix the problem:

```
$ brew install openssl
$ brew list openssl
/usr/local/Cellar/openssl/1.0.2e/bin/c_rehash
/usr/local/Cellar/openssl/1.0.2e/bin/openssl
/usr/local/Cellar/openssl/1.0.2e/include/openssl/ (75 files) <<<<<<<<<<<<<<
/usr/local/Cellar/openssl/1.0.2e/lib/libcrypto.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2e/lib/libssl.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2e/lib/engines/ (12 files)
/usr/local/Cellar/openssl/1.0.2e/lib/pkgconfig/ (3 files)
/usr/local/Cellar/openssl/1.0.2e/lib/ (4 other files)
/usr/local/Cellar/openssl/1.0.2e/share/man/ (1543 files)
$ cd $VERNEMQ
$ CFLAGS="-I /usr/local/Cellar/openssl/1.0.2e/include" make rel
```

**Comment by syberkitten** [comment]
Had the same issue, after trying the above solution I get this error:
Unable to rewrite .app file /Users/xx/Documents/dev/erlang/vernemq/_build/default/rel/vernemq/lib/syntax_tools-2.1.1/ebin/syntax_tools.app due to {error, eacces}

**Comment by ioolkos** [comment]
Hi @syberkitten, 
have you also tried this: https://github.com/erlio/vernemq/issues/119#issuecomment-214714457 ?
(its just brew install and brew link for openssl)

**Comment by syberkitten** [comment]
Thanks, I haven't tried linking.... but when I do , i get this:

Warning: **Refusing to link: openssl**
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib

I'm exactly sure what to link with what now ...

**Comment by syberkitten** [comment]
found the same issue in a different project:
https://github.com/dotnet/cli/issues/3964

forcing it does not work as well:
`brew link --force openssl`

**Comment by ioolkos** [comment]
Hm, ok, thanks @syberkitten 
tried to google around a little... now I'm confused myself by OS X and OpenSSL ;)

**Comment by larshesel** [comment]
A long shot: there's an issue which looks similar to what you experienced (eacces) in relx (part of rebar3): https://github.com/erlware/relx/issues/583

Maybe the fix for this issue was included in the latest rebar3 (v3.4.1 - downloadable here: http://www.rebar3.org/). Maybe you could try and drop that into your vernemq repo overwriting the old one (which was version v3.3.6 if you trying to compile VerneMQ 1.0.1+) and see if that changes things (remember to clear out the old build first.

**Comment by lucasterra** [comment]
Hey. Just commenting here to let you know how I managed to make it work...

Had to follow @larshesel suggestion and overwrite `rebar3` at `vernemq`'s folder. And forced it to use my OpenSSL files.

```
cd vernemq
chmod +x rebar3
CFLAGS="-I/usr/local/Cellar/openssl/1.0.2l/include -L/usr/local/Cellar/openssl/1.0.2l/lib" make rel
```

**Comment by ioolkos** [comment]
Hi @lucasterra awesome! :)

Thanks a lot for taking the time and effort to document this! this is a useful future reference.

**Comment by lucasterra** [comment]
To anyone trying to compile right now, keep in mind that you need Erlang/OTP 19.x, not 20.x (see #426).

Thought it was worth mentioning because `brew install erlang` will get you 20.x.

**Comment by syberkitten** [comment]
Have tried with: `Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]`

Still failing ... the 'make' output:
`vmq_passwd.c:32:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
Reaping losing child 0x7ffd14403020 PID 97923
make[1]: *** [compile] Error 1
Removing child 0x7ffd14403020 PID 97923 from chain.
===> Hook for compile failed!`

**Comment by larshesel** [comment]
@syberkitten this is likely due to the fact that Apple no longer ships the OpenSSL development header files with OSX. You need to install those manually - googling for it might turn up something useful: https://www.google.com/search?q=mac+osx+%27openssl%2Fevp.h%27+file+not+found (I'm not using OSX myself)

**Comment by syberkitten** [comment]
Issue is resolved using a solution that worked for me in this issue:
https://github.com/erlio/vernemq/issues/88

which is adding a MakeFile flags with proper locations to the installed OpenSSL on the operating system.

final result:
```
CC?=	gcc

compile:
	$(CC) $(CFLAGS) vmq_passwd.c -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -lcrypto -o ../priv/vmq_passwd
```

Now the code compiles on El-Capitan using Erlang OTP/19.3  :)

**Comment by weerada-moria** [comment]
===> Verifying dependencies...
===> Compiling eper
===> Compiling _build/default/lib/eper/src/redbug.erl failed
_build/default/lib/eper/src/redbug.erl:141: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
_build/default/lib/eper/src/redbug.erl:267: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

make: *** [rel] Error 1


i got this problem how can i fix it? pls help   thank you

**Comment by larshesel** [comment]
@weerada-moria you're compiling with Erlang/OTP 21 which is not yet supported, see #738
