### ISSUE TITLE
Does not compile on OSX

### ISSUE THREAD

**Issue by teodor-pripoae** [erlio/vernemq#74]
Running `make` or `make rel` after cloning the repository fails. Tested this on 2 Mac OS X computers running 10.9 and 10.10.

```
Undefined symbols for architecture x86_64:
  "std::string::rfind(char, unsigned long) const", referenced from:
      leveldb::(anonymous namespace)::Repairer::ArchiveFile(std::string const&, bool) in libleveldb.a(repair.o)
  "std::string::compare(char const*) const", referenced from:
      leveldb::VersionSet::Recover() in libleveldb.a(version_set.o)
  "std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const", referenced from:
      eleveldb::eleveldb_thread_pool::grow_thread_pool(unsigned long) in threading.o
  "std::ostream& std::ostream::_M_insert<unsigned long>(unsigned long)", referenced from:
      eleveldb::eleveldb_thread_pool::grow_thread_pool(unsigned long) in threading.o
  "std::string::_M_leak_hard()", referenced from:
      leveldb::WriteBatchInternal::SetCount(leveldb::WriteBatch*, int) in libleveldb.a(write_batch.o)
      leveldb::WriteBatchInternal::SetSequence(leveldb::WriteBatch*, unsigned long long) in libleveldb.a(write_batch.o)
      leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&) in libleveldb.a(write_batch.o)
      leveldb::WriteBatch::Delete(leveldb::Slice const&) in libleveldb.a(write_batch.o)
      leveldb::WriteBatchInternal::Append(leveldb::WriteBatch*, leveldb::WriteBatch const*) in libleveldb.a(write_batch.o)
      leveldb::(anonymous namespace)::BloomFilterPolicy2::CreateFilter(leveldb::Slice const*, int, std::string*) const in libleveldb.a(bloom2.o)
      leveldb::VersionSet::Recover() in libleveldb.a(version_set.o)
      ...
```

**Comment by teodor-pripoae** [comment]
I fixed this by overriding eleveldb dependency to use the latest git commit from basho repository. Is there any reason for using the helium fork ?

Then, it fails to compile the syslog module.

```
Undefined symbols for architecture x86_64:
  "_driver_alloc", referenced from:
      _syslogdrv_start in syslog_drv.o
      _syslogdrv_control in syslog_drv.o
  "_driver_free", referenced from:
      _syslogdrv_stop in syslog_drv.o
      _syslogdrv_control in syslog_drv.o
  "_set_port_control_flags", referenced from:
      _syslogdrv_start in syslog_drv.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/Users/toni/code/gh/vernemq/_build/default/lib/syslog/c_src/../priv/syslog_drv.so] Error 1
```

After removing the override from rebar.config everything compiles.

**Comment by teodor-pripoae** [comment]
Ah, it seems it crashes on start if using the basho eleveldb. Is there any other option to compile on OSX 10.9/10.10 ?

```
$ _build/default/rel/vernemq/bin/vernemq console
config is OK
-config /Users/toni/code/gh/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2015.11.23.01.24.46.config -args_file /Users/toni/code/gh/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2015.11.23.01.24.46.args -vm_args /Users/toni/code/gh/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2015.11.23.01.24.46.args
!!!!
!!!! WARNING: ulimit -n is 10000; 65536 is the recommended minimum.
!!!!
Exec:  /Users/toni/code/gh/vernemq/_build/default/rel/vernemq/bin/../erts-6.3.1/bin/erlexec -boot /Users/toni/code/gh/vernemq/_build/default/rel/vernemq/bin/../releases/0.12.3/vernemq               -config /Users/toni/code/gh/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2015.11.23.01.24.46.config -args_file /Users/toni/code/gh/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2015.11.23.01.24.46.args -vm_args /Users/toni/code/gh/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2015.11.23.01.24.46.args              -pa /Users/toni/code/gh/vernemq/_build/default/rel/vernemq/bin/../lib/erlio-patches -- console
Root: /Users/toni/code/gh/vernemq/_build/default/rel/vernemq/bin/..
Erlang/OTP 17 [erts-6.3.1] [source] [64-bit] [smp:4:4] [async-threads:64] [hipe] [kernel-poll:true] [dtrace]

Setup running ...
Directories verified. Res = {[ok],[]}
Setup finished processing hooks ...
{"Kernel pid terminated",application_controller,"{application_start_failure,plumtree,{{error,{shutdown,{failed_to_start_child,plumtree_metadata_leveldb_instance_sup,{shutdown,{failed_to_start_child,plmtrlvld_0,{undef,[{eleveldb,validate_options,[open,[{create_if_missing,true},{included_applications,[]},{sync,false},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,57336746}]],[]},{plumtree_metadata_leveldb_instance,init_state,2,[{file,\"/Users/toni/code/gh/vernemq/_build/default/lib/plumtree/src/plumtree_metadata_leveldb_instance.erl\"},{line,299}]},{plumtree_metadata_leveldb_instance,init,1,[{file,\"/Users/toni/code/gh/vernemq/_build/default/lib/plumtree/src/plumtree_metadata_leveldb_instance.erl\"},{line,131}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]}}}}}},{plumtree_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,plumtree,{{error,{shutdown,{failed_to_start_child,plumtree_metadata_leveldb_instance_sup,{shutdown,{failed_to_start_child,p
```

**Comment by ioolkos** [comment]
I take it you have a standard install of the Apple Dev tools?
Compilation should at least work on 10.9

For 10.10, we have an open issue #68 related to the SSL libs.

**Comment by teodor-pripoae** [comment]
Well, I have all the tools installed, and I'm able to compile eleveldb from source when pulled from their github repository.

The only non standard install is that I have homebrew root in `/opt/boxen/homebrew` instead of `/usr/local`.

**Comment by ioolkos** [comment]
@teodor-pripoae have you still worked on this? have you reached further insights you can share?
Thanks for your work!

**Comment by teodor-pripoae** [comment]
No, I just gave up and installed it on a vagrant virtual machine using the deb release.

**Comment by ioolkos** [comment]
Just confirmed VerneMQ fresh clone compiles on OS X 10.9.

**Comment by phantanthanh1996** [comment]
Hi @teodor-pripoae, i am gotten same problem so could you pls talk how to fix it? 
Thank you!

**Comment by teodor-pripoae** [comment]
I've installed it in a linux virtual machine using official deb files.

**Comment by arunkbharathan** [comment]
I'm trying to build vernemq from sources. Followed the instructions given in https://vernemq.com/downloads/
The following is the result.

===> Fetching rebar3_cuttlefish ({git,
                                         "git://github.com/larshesel/rebar3_cuttlefish",
                                         {branch,
                                          "use-otp20-compatibly-cuttlefish"}})
===> Fetching cuttlefish ({git,
                                  "git://github.com/kyorai/cuttlefish.git",
                                  {ref,
                                   "649cda2828ef939126a20faa5d0ee0a2ab69f9a6"}})
===> Fetching getopt ({pkg,<<"getopt">>,<<"0.8.2">>})
make: *** [rel] Segmentation fault: 11

I'm using enterprise distribution of erlang(18.2) and the OS version Mac OS high sierra.

Any solutions for this?
